### ISSUE TITLE
Description not being set

### ISSUE THREAD

**Issue by CarrotManMatt** [flying-sheep/hatch-docstring-description#72]
Really appreciate you making this plugin for building with hatch. However when creating a build the description never seems to get set.

Here is my `pyproject.toml`:
```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatch-docstring-description", "hatch-vcs", "hatchling"]

[project]
authors = [ ... ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development",
    "Typing :: Typed",
]
dynamic = ["description", "version"]
keywords = [ ... ]
maintainers = [ ... ]
name = " ... "
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Issues = "https://github.com/..."
Repository = "https://github.com/..."

[tool.hatch.build]
only-packages = true

[tool.hatch.version]
raw-options = { local_scheme = "no-local-version", version_scheme = "python-simplified-semver" }
source = "vcs"
```

(The `...` values have correct values that have been removed for brevity).

I then run `hatch build`, and yet the outputted source-dist has `Dynamic: Summary` within the `PKG-INFO` file. Is this supposed to happen, or am I running into a bug?
